"""
Django settings for ClimateQuest project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from .base_settings import *

SECRET_KEY = 'django-insecure-xn1bs&mroh!s0bsc$nvm9ob&fhr%_s2k-v9o7xra-we8(k4*3p'

DEBUG = False

ALLOWED_HOSTS = [
    'localhost',
    '192.168.178.120',
    '127.0.0.1',
    '10.0.2.2'
]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


INTERNAL_IPS = [
    '127.0.0.1',
]