"""
Django settings for ClimateQuest project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from .settingsprod import *
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'backup-test',
        'USER': 'climatequestuser',
        'PASSWORD': os.environ.get("DB_PASSWORD", ""),
        'HOST': 'localhost',
        'PORT': '',
    }
}