# Generated by Django 6.0 on 2026-01-15 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='families', to=settings.AUTH_USER_MODEL),
        ),
    ]
