# Generated by Django 5.2.3 on 2025-09-04 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='ForumPost',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='forum_post',
        ),
    ]
