# Generated by Django 5.2.3 on 2025-09-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_question_forumpost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forumpost',
            old_name='created_at',
            new_name='date_time',
        ),
    ]
