# Generated by Django 5.2.3 on 2025-09-05 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_rename_created_at_forumpost_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='created_at',
            new_name='date_time',
        ),
    ]
