# Generated by Django 6.0 on 2026-02-05 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='petitions/'),
        ),
        migrations.AlterField(
            model_name='petition',
            name='signs',
            field=models.ManyToManyField(blank=True, null=True, related_name='petition_sign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='petition',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_update', to='petitions.update'),
        ),
    ]
