# Generated by Django 6.0 on 2026-02-06 12:43

import core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0002_alter_petition_img_alter_petition_signs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='update',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_update', to='petitions.update', validators=[core.validators.validate_image]),
        ),
    ]
