# Generated by Django 6.0 on 2026-02-06 12:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0004_alter_petition_img_alter_petition_update'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='signs',
            field=models.ManyToManyField(blank=True, related_name='petition_sign', to=settings.AUTH_USER_MODEL),
        ),
    ]
