# Generated by Django 6.0 on 2026-02-07 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0006_category_petition_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='petition_category', to='petitions.category'),
        ),
    ]
