# Generated by Django 6.0 on 2026-02-07 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0007_alter_petition_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='category',
        ),
    ]
