# Generated by Django 6.0 on 2026-02-07 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0008_remove_petition_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='petition_category', to='petitions.category'),
            preserve_default=False,
        ),
    ]
