# Generated by Django 6.0 on 2026-02-09 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0009_petition_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='creator',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, related_name='petition_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
