# Generated by Django 6.0 on 2026-02-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0011_alter_petition_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='creator',
        ),
    ]
