# Generated by Django 6.0 on 2026-02-09 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0014_alter_petition_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='updated_at',
        ),
    ]
