# Generated by Django 6.0 on 2026-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0015_remove_petition_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='update',
        ),
        migrations.AddField(
            model_name='petition',
            name='updates',
            field=models.ManyToManyField(null=True, related_name='petition_update', to='petitions.update'),
        ),
    ]
