# Generated by Django 6.0 on 2026-02-09 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0016_remove_petition_update_petition_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='updates',
            field=models.ManyToManyField(blank=True, related_name='petition_update', to='petitions.update'),
        ),
    ]
