# Generated by Django 6.0 on 2026-02-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0018_answer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='comments',
            field=models.ManyToManyField(related_name='petition_comment', to='petitions.comment'),
        ),
    ]
