# Generated by Django 6.0 on 2026-02-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0019_petition_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='goal',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
