# Generated by Django 6.0 on 2026-02-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0020_petition_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
