# Generated by Django 6.0.2 on 2026-02-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0021_petition_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='img',
        ),
    ]
