# Generated by Django 6.0.2 on 2026-02-19 15:29

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0022_remove_petition_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='petitions/', validators=[core.validators.validate_image]),
        ),
    ]
