# Generated by Django 6.0.2 on 2026-02-19 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0023_petition_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petition',
            name='img',
        ),
    ]
