# Generated by Django 6.0 on 2026-05-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0024_remove_petition_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='petition',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='content_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='update',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
