# Generated by Django 6.0 on 2026-05-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petitions', '0025_petition_content_de_petition_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petition',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='petition_comment', to='petitions.comment'),
        ),
    ]
