# Generated by Django 5.2.3 on 2025-12-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='chat',
            field=models.BooleanField(default=True),
        ),
    ]
