# Generated by Django 6.0 on 2026-01-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_chat'),
        ('family', '0002_alter_family_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='communities', to='family.family'),
        ),
    ]
