# Generated by Django 6.0 on 2026-01-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererweitert',
            name='weekly_goal',
            field=models.IntegerField(default=20),
        ),
    ]
