# Generated by Django 5.2.3 on 2025-11-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererweitert',
            name='mail_verified',
            field=models.BooleanField(default=False),
        ),
    ]
