# Generated by Django 5.2.3 on 2025-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0002_usererweitert_mail_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererweitert',
            name='statement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='VerificationCode',
        ),
    ]
