# Generated by Django 6.0 on 2026-01-25 16:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0002_usererweitert_weekly_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usererweitert',
            name='weekly_goal',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
