# Generated by Django 5.2.3 on 2025-11-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0003_usererweitert_statement_delete_verificationcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usererweitert',
            name='statement',
            field=models.TextField(default='Hallo. Ich benutze ClimateQuest.'),
        ),
    ]
