# Generated by Django 6.0.2 on 2026-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0003_alter_usererweitert_weekly_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererweitert',
            name='given_credits',
            field=models.IntegerField(default=0),
        ),
    ]
