# Generated by Django 6.0.2 on 2026-03-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0005_alter_usererweitert_given_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererweitert',
            name='allows_data_view',
            field=models.BooleanField(default=False),
        ),
    ]
