# Generated by Django 6.0.2 on 2026-03-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0006_usererweitert_allows_data_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreeCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('redeemURL', models.URLField()),
                ('sponsor', models.CharField(max_length=100)),
                ('planted', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='usererweitert',
            name='given_credits',
        ),
        migrations.AddField(
            model_name='usererweitert',
            name='planted_trees',
            field=models.ManyToManyField(to='personals.treecodes'),
        ),
    ]
