# Generated by Django 6.0 on 2026-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0007_treecodes_remove_usererweitert_given_credits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usererweitert',
            name='planted_trees',
            field=models.ManyToManyField(blank=True, to='personals.treecodes'),
        ),
    ]
