# Generated by Django 6.0 on 2026-04-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0008_alter_usererweitert_planted_trees'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererweitert',
            name='lang',
            field=models.CharField(default='de', max_length=2),
        ),
    ]
