# Generated by Django 6.0 on 2026-04-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0009_usererweitert_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='description_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
