# Generated by Django 6.0 on 2026-05-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0010_level_description_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererweitert',
            name='additional_klimapunkte',
            field=models.BooleanField(default=0),
        ),
    ]
