# Generated by Django 6.0 on 2026-05-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0011_usererweitert_additional_klimapunkte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usererweitert',
            name='additional_klimapunkte',
            field=models.FloatField(default=0),
        ),
    ]
