# Generated by Django 6.0 on 2026-05-02 19:17

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('personals', '0012_alter_usererweitert_additional_klimapunkte'), ('personals', '0013_remove_usererweitert_additional_klimapunkte')]

    dependencies = [
        ('personals', '0011_usererweitert_additional_klimapunkte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usererweitert',
            name='additional_klimapunkte',
        ),
    ]
