# Generated by Django 6.0 on 2026-05-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0012_alter_usererweitert_additional_klimapunkte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usererweitert',
            name='additional_klimapunkte',
        ),
    ]
