# Generated by Django 6.0 on 2026-05-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0012_alter_usererweitert_additional_klimapunkte_squashed_0013_remove_usererweitert_additional_klimapunkte'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererweitert',
            name='additional_klimapunkte',
            field=models.FloatField(default=0),
        ),
    ]
