# Generated by Django 6.0 on 2026-05-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personals', '0014_usererweitert_additional_klimapunkte'),
    ]

    operations = [
        migrations.AddField(
            model_name='usererweitert',
            name='show_tour_banner',
            field=models.BooleanField(default=True),
        ),
    ]
