# Generated by Django 6.0.2 on 2026-03-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='benachrichtigung',
            name='url',
            field=models.URLField(default='/dashboard/', max_length=500),
        ),
    ]
