# Generated by Django 6.0.2 on 2026-03-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_benachrichtigung_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benachrichtigung',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
