# Generated by Django 6.0 on 2026-04-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_benachrichtigung_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benachrichtigung',
            old_name='benachrichtigung',
            new_name='benachrichtigung_de',
        ),
        migrations.AddField(
            model_name='benachrichtigung',
            name='benachrichtigung_en',
            field=models.CharField(default='This notification is currently only available in German. All notifications sent after April 27th, 2026 will be available in English, too.', max_length=500),
            preserve_default=False,
        ),
    ]
