# Generated by Django 6.0 on 2026-05-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_reporteduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporteduser',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
