# Generated by Django 6.0 on 2026-05-24 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_reporteduser_reviewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benachrichtigung',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
