# Generated by Django 5.2.3 on 2025-11-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='good',
            field=models.IntegerField(default=0),
        ),
    ]
