# Generated by Django 5.2.3 on 2025-08-26 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 26, 12, 50, 14, 771401, tzinfo=datetime.timezone.utc)),
        ),
    ]
