# Generated by Django 5.2.3 on 2025-11-19 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_artikel_good'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='good',
        ),
        migrations.AddField(
            model_name='artikel',
            name='good',
            field=models.ManyToManyField(blank=True, related_name='artikel_good', to=settings.AUTH_USER_MODEL),
        ),
    ]
