# Generated by Django 6.0 on 2026-02-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_alter_artikel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='date_time',
            field=models.DateField(auto_now=True),
        ),
    ]
