# Generated by Django 5.2.3 on 2025-08-26 12:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_alter_artikel_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
