# Generated by Django 5.2.3 on 2025-11-19 12:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_remove_artikel_good_artikel_good'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artikel',
            name='good',
        ),
        migrations.AddField(
            model_name='artikel',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='artikel_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
