# Generated by Django 6.0.2 on 2026-02-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_alter_artikel_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='msg_if_wrong',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artikel',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
