# Generated by Django 6.0.2 on 2026-02-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_artikel_msg_if_wrong_artikel_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artikel',
            name='msg_if_wrong',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
