# Generated by Django 5.2.3 on 2025-09-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_remove_artikel_questions_comment_artikel_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artikel',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
