# Generated by Django 6.0 on 2026-04-13 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0006_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='artikel',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artikel_category', to='artikel.category'),
            preserve_default=False,
        ),
    ]
