# Generated by Django 6.0 on 2026-05-04 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0007_artikel_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='date_time',
            new_name='updated_at',
        ),
    ]
