# Generated by Django 6.0 on 2026-05-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0008_rename_date_time_artikel_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='content',
            new_name='content_de',
        ),
        migrations.AddField(
            model_name='artikel',
            name='content_en',
            field=models.TextField(default='No English translation yet'),
            preserve_default=False,
        ),
    ]
