# Generated by Django 6.0 on 2026-05-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0009_rename_content_artikel_content_de_artikel_content_en'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='name',
            new_name='name_de',
        ),
        migrations.AddField(
            model_name='artikel',
            name='name_en',
            field=models.CharField(default='No translation available yet', max_length=100),
            preserve_default=False,
        ),
    ]
