# Generated by Django 6.0 on 2026-07-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0011_artikel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_de',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
