# Generated by Django 5.2.3 on 2025-08-26 08:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AktionenListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('klimapunkte', models.FloatField()),
                ('mengeBeschreibung', models.CharField(blank=True, max_length=200, null=True)),
                ('anmerkung', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aktion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('quantity', models.FloatField(null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('aktion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='verbrauch.aktionenliste')),
            ],
        ),
    ]
