# Generated by Django 6.0 on 2026-01-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktionenliste',
            name='mengeBeschreibungSingular',
            field=models.CharField(default=models.CharField(max_length=100), max_length=100),
        ),
        migrations.AlterField(
            model_name='aktion',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aktionenliste',
            name='mengeBeschreibung',
            field=models.CharField(max_length=100),
        ),
    ]
