# Generated by Django 6.0 on 2026-01-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0003_aktionenliste_mengebeschreibungsingular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktion',
            name='aktion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aktionen.aktionenliste'),
        ),
        migrations.AlterField(
            model_name='category',
            name='actions',
            field=models.ManyToManyField(related_name='category', to='aktionen.aktionenliste'),
        ),
    ]
