# Generated by Django 6.0 on 2026-01-06 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0004_alter_aktion_aktion_alter_category_actions'),
    ]

    operations = [
    ]
