# Generated by Django 6.0 on 2026-01-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0005_rename_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktionenliste',
            name='max',
            field=models.FloatField(default=0.0),
        ),
    ]
