# Generated by Django 6.0.2 on 2026-03-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0006_aktionenliste_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktionenliste',
            name='mengeBeschreibungSingular',
            field=models.CharField(max_length=100),
        ),
    ]
