# Generated by Django 6.0 on 2026-04-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0007_alter_aktionenliste_mengebeschreibungsingular'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktionenliste',
            name='track_distance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aktionenliste',
            name='track_timely',
            field=models.BooleanField(default=False),
        ),
    ]
