# Generated by Django 6.0 on 2026-04-17 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0008_aktionenliste_track_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aktionenliste',
            old_name='track_timely',
            new_name='track_weekly',
        ),
    ]
