# Generated by Django 6.0 on 2026-04-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0010_trackedactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aktionenliste',
            old_name='track_distance',
            new_name='track_kilometerly',
        ),
    ]
