# Generated by Django 6.0 on 2026-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0011_rename_track_distance_aktionenliste_track_kilometerly'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktionenliste',
            name='anmerkung_en',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='aktionenliste',
            name='mengeBeschreibungSingular_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aktionenliste',
            name='mengeBeschreibung_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aktionenliste',
            name='name_en',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aktionenliste',
            name='source_en',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
