# Generated by Django 6.0 on 2026-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0012_aktionenliste_anmerkung_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktionenliste',
            name='anmerkung_en',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='aktionenliste',
            name='mengeBeschreibungSingular_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aktionenliste',
            name='mengeBeschreibung_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aktionenliste',
            name='name_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aktionenliste',
            name='source_en',
            field=models.CharField(max_length=1000),
        ),
    ]
