# Generated by Django 6.0 on 2026-04-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0013_alter_aktionenliste_anmerkung_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
