# Generated by Django 6.0 on 2026-05-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0014_category_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktionenliste',
            name='forbidden_in_same_period',
            field=models.ManyToManyField(blank=True, null=True, related_name='forbidden_actions_in_same_period', to='aktionen.aktionenliste'),
        ),
    ]
