# Generated by Django 6.0 on 2026-05-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0015_aktionenliste_forbidden_in_same_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktionenliste',
            name='forbidden_in_same_period',
            field=models.ManyToManyField(blank=True, to='aktionen.aktionenliste'),
        ),
    ]
