# Generated by Django 6.0 on 2026-05-29 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aktionen', '0016_alter_aktionenliste_forbidden_in_same_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='actions',
        ),
        migrations.AddField(
            model_name='aktionenliste',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='aktionen.category'),
        ),
    ]
