# Generated by Django 6.0 on 2026-05-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_fame', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='halloffameentry',
            old_name='description',
            new_name='description_de',
        ),
        migrations.AddField(
            model_name='halloffameentry',
            name='description_en',
            field=models.TextField(default='en description'),
            preserve_default=False,
        ),
    ]
