# Generated by Django 6.0 on 2026-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_fame', '0002_rename_description_halloffameentry_description_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffameentry',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
