# Generated by Django 6.0 on 2026-05-20 17:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_fame', '0003_alter_halloffameentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halloffameentry',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
