# Generated by Django 6.0 on 2026-05-22 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hall_of_fame', '0004_alter_halloffameentry_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallOfFameData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks_count', models.PositiveIntegerField(default=0)),
                ('to_do_de', models.CharField(max_length=500)),
                ('to_do_en', models.CharField(max_length=500)),
            ],
        ),
    ]
